### PR TITLE
fix: use Decimal instead of bare floating point numbers

### PR DESCRIPTION
**Pull request by spacekpe**

### CODE REVIEW

**Comment by spacekpe** [comment]
I categoried this as "fix" because this deficiency has caused me to pay 1 CZK less in taxes than I owed :facepalm:

Anyway, I can see that opinions might vary. Not sure if it is worth a major version number or not, but I think that in some form or shape this definitely should be addressed.

**Comment by honzajavorek** [comment]
Ah, this is awesome! I wanted to do this for a long time, but I didn't know you can instruct the JSON parser to do this, so I thought the change would be difficult to do and would need more work. I think I'll bump the major number anyway, I want to do a bit of cleanup around the repo when I have a bit of time, and then cut a new release.

**Comment by honzajavorek** [comment]
I think I came up with a way how to allow this change but keep bc compatibility for now https://github.com/honzajavorek/fiobank/commit/a0f8b0edce5b2da6a63f957d8683fc677f2c57f1 (I'm sorry for the diff, I didn't realize before commit that my editor re-formats the code automatically).

**Comment by honzajavorek** [comment]
Final solution in the released version is

```python
client = FioBank(token='...', decimal=True)
```

**Pull request merged**
