### PR TITLE
Uggly little typo...

### PR DESCRIPTION
**Pull request by Visgean**
identifiaction -> identification, note: this might cause some backwards compatibility issues.

### CODE REVIEW

**Comment by honzajavorek** [comment]
Thanks! Could you please bump minor version in `setup.py`?

**Comment by Visgean** [comment]
Done.

**Comment by honzajavorek** [comment]
Thanks! I am going to merge this and release a new version until the end of this week (cannot do it today or tomorrow easily).

**Comment by honzajavorek** [comment]
:balloon:

**Comment by honzajavorek** [comment]
@Visgean I mentioned the incompatibility in description of the newest release: https://github.com/honzajavorek/fiobank/releases/tag/v0.0.5 Thank you again.

**Pull request merged**
