### PR TITLE
Added: sending money (API import method).

### PR DESCRIPTION
**Pull request by im-n1**
Hey, hi, hello,

I've incorporated your library to my project and it works flawlessly, so big thank you.

However I've needed to add ability of sending money (Fio import method) so I did so.
1. New method `send` (because import is keyword)
2. Updated readme with an example.
3. Added new dependency `xmltodict`
4. Bumped to 0.1 because I've used the lib for a quite time and haven't found any bugs.

Please let me know you thoughts ;)

Cia on pyvo :)

### CODE REVIEW

**Comment by honzajavorek** [comment]
Hi, thank you very much for the contribution, it's awesome! This is still
in my queue, but I promise I'll get to review this. I definitely want this
feature in and I think not only me!

**Comment by grafa** [comment]
Cool,

let me know when you are ready then.

Cheers.

**Comment by honzajavorek** [comment]
If I understand correctly, this should implement #10, right?

**Comment by grafa** [comment]
Hi,

The link #10 is to this page. I'm confused...

**Comment by honzajavorek** [comment]
Ah, sorry, I meant #1. GitHub probably suggested me the zero and I didn't notice that.

**Comment by honzajavorek** [comment]
If I understand correctly, this should implement #1, right?

**Comment by grafa** [comment]
Yes

**Comment by honzajavorek** [comment]
@grafa So after some time I'm getting back to maintaining this library and I'd like to incorporate your changes. However, a lot of things have changed since. If you feel like you would like to get back to this, please

- rebase the PR on top of current master
- format your commits according to _conventional changelog_ so [semantic releasing](https://github.com/relekang/python-semantic-release) can correctly detect changes (recent commits in master can be your guide)
- please try to add tests (existing tests can be your guide)

**Comment by grafa** [comment]
Hi there,

unfortunately I'm to busy to help you with this task. Feel free to dive into that.

Thanks.

**Comment by honzajavorek** [comment]
I didn't manage to get this done and there hasn't been a big ask for this feature. I'm sorry this didn't work out! Thanks for your work anyway, it's still appreciated 🙏 I'll close this and anyone feeling like following up is free to comment.

**Pull request closed without merging**
