### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by scervenka03**

### CODE REVIEW

**Comment by scervenka03** [comment]
I'd rather you wouldn't ask 😄, it was supposed to be into master of our fork ☹️

**Comment by honzajavorek** [comment]
I will ask! What is the main reason for the fork to exist? Is there a feature the library should implement?

**Comment by scervenka03** [comment]
It's less about missing features and more about the certainty that the package is not going to suddenly disappear one day. 

Thank you for maintaining this 😄, it is great to use.

**Comment by honzajavorek** [comment]
I see, ok! Shameless plug - the certainty can be raised [here](https://github.com/sponsors/honzajavorek/), too 😉

**Pull request closed without merging**
